// dummyData.ts

import { v4 as uuid } from "uuid";

export const collectionId = uuid();

export const products = [
  {
    id: uuid(),
    title: "Graphic Street Tee",
    slug: "graphic-street-tee",
    description: "A trendy streetwear graphic tee for everyday casual look.",
    basePrice: 1099.00,
    salePrice: 999.00,
    rating: 4.7,
    reviews: 89,
    isFeatured: false,
    isBestSeller: true,
    isNew: true,
    isOnSale: true,
    isActive: true,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Grey"],
    metaTitle: "Graphic Street Tee",
    metaDescription: "Elevate your street style with this bold graphic printed t-shirt.",
    collectionId,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuid(),
    title: "Classic White Tee",
    slug: "classic-white-tee",
    description: "A timeless classic white t-shirt made from 100% organic cotton.",
    basePrice: 799.00,
    salePrice: 699.00,
    rating: 4.5,
    reviews: 127,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isOnSale: true,
    isActive: true,
    sizes: ["S", "M", "L", "XL"],
    colors: ["White"],
    metaTitle: "Classic White Tee",
    metaDescription: "Stay stylish with this classic white tee made of organic cotton.",
    collectionId,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuid(),
    title: "V-Neck Slim Fit",
    slug: "v-neck-slim-fit",
    description: "A slim-fit V-neck tee for that modern, sharp look.",
    basePrice: 899.00,
    salePrice: 749.00,
    rating: 4.3,
    reviews: 54,
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    isOnSale: true,
    isActive: true,
    sizes: ["M", "L", "XL"],
    colors: ["Navy", "Black"],
    metaTitle: "V-Neck Slim Fit Tee",
    metaDescription: "Cut slim, fit smart—our V-neck tee is the modern essential.",
    collectionId,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuid(),
    title: "Long Sleeve Comfort",
    slug: "long-sleeve-comfort",
    description: "Soft long-sleeve tee for cooler days, with extra stretch.",
    basePrice: 1199.00,
    salePrice: 999.00,
    rating: 4.8,
    reviews: 200,
    isFeatured: true,
    isBestSeller: false,
    isNew: false,
    isOnSale: true,
    isActive: true,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Charcoal", "White"],
    metaTitle: "Long Sleeve Comfort Tee",
    metaDescription: "Stay warm and comfortable in this soft stretch long-sleeve tee.",
    collectionId,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: uuid(),
    title: "Performance Polo",
    slug: "performance-polo",
    description: "A moisture-wicking polo for active days or casual Fridays.",
    basePrice: 1499.00,
    salePrice: 1299.00,
    rating: 4.2,
    reviews: 75,
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    isOnSale: false,
    isActive: true,
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Grey"],
    metaTitle: "Performance Polo Shirt",
    metaDescription: "Keep cool and look sharp with our performance polo.",
    collectionId,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const productImages = products.flatMap((p) => [
  {
    id: uuid(),
    productId: p.id,
    url: `https://picsum.photos/seed/${p.slug}-1/600/800`,
    color: p.colors[0],
    alt: `${p.title} image 1`,
    position: 1,
  },
  {
    id: uuid(),
    productId: p.id,
    url: `https://picsum.photos/seed/${p.slug}-2/600/800`,
    color: p.colors[0],
    alt: `${p.title} image 2`,
    position: 2,
  },
]);
