import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter, Unbounded } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import { CartProvider } from "@/components/Cart/CartContext";

export const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
export const unbounded = Unbounded({
  subsets: ["latin"],
  variable: "--font-unbounded",
});

export const metadata: Metadata = {
  title: "Vistara Styles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.variable} ${unbounded.variable} bg-black font-sans`}
        >
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
            <Toaster
              position="top-right"
              closeButton
              duration={2000}
              containerAriaLabel="Toaster"
            />
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
